In [1]:
import pandas as pd

             x         y
0     664159.0  550946.0
1     665845.0  557965.0
2     597173.0  575538.0
3     618600.0  551446.0
4     635690.0  608046.0
5     588100.0  557588.0
6     582015.0  546191.0
7     604678.0  574577.0
8     572029.0  518313.0
9     604737.0  574591.0
10    577728.0  587566.0
11    602013.0  574722.0
12    627968.0  574625.0
13    607269.0  536961.0
14    603145.0  574795.0
15    671919.0  571761.0
16    612184.0  570393.0
17    600032.0  575310.0
18    627912.0  593892.0
19    601967.0  604428.0
20    591851.0  569051.0
21    601444.0  572693.0
22    629718.0  558104.0
23    661430.0  603567.0
24    597551.0  556737.0
25    601182.0  582584.0
26    562704.0  570596.0
27    605107.0  563429.0
28    607214.0  575069.0
29    568824.0  570203.0
...        ...       ...
4970  675357.0  870850.0
4971  673449.0  860643.0
4972  687325.0  883004.0
4973  603472.0  894573.0
4974  669713.0  851017.0
4975  693362.0  837786.0
4976  605535.0  925341.0
4977  687078.0  791051.0
4978  672387.0  800443.0
4979  683048.0  937776.0
4980  713579.0  879202.0
4981  571669.0  873544.0
4982  695260.0  824882.0
4983  702654.0  841548.0
4984  601619.0  825604.0
4985  564416.0  878492.0
4986  703773.0  870419.0
4987  674931.0  870112.0
4988  673140.0  864863.0
4989  681053.0  892766.0
4990  683321.0  873932.0
4991  701017.0  931252.0
4992  645677.0  814395.0
4993  677362.0  853471.0
4994  659046.0  930099.0
4995  665426.0  853940.0
4996  691827.0  863963.0
4997  650661.0  861267.0
4998  599647.0  858702.0
4999  684091.0  842566.0

[5000 rows x 2 columns]